### ISSUE TITLE
AbstractMethodError

### ISSUE THREAD

**Issue by JrmyDev** [shannah/cn1-websockets#8]
Hi Steve.
I've installed library via cn1lib manager of my project and then refresh cn1lib.

When I launch my application on simulator, I obtain this message : 
`java.lang.AbstractMethodError: com.codename1.io.websocket.WebSocketNativeImplImpl.getReadyState()I
About to start socket
Sending connect
	at com.codename1.io.websocket.WebSocket.getReadyState(WebSocket.java:229)
	at com.codename1.io.websocket.WebSocket.connect(WebSocket.java:199)
	at com.amplitude.tablet.MainClass.showChat(MainClass.java:136)
	at com.amplitude.tablet.MainClass.start(MainClass.java:257)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.codename1.impl.javase.Executor$1$1.run(Executor.java:123)
	at com.codename1.ui.Display.processSerialCalls(Display.java:1154)
	at com.codename1.ui.Display.mainEDTLoop(Display.java:971)
	at com.codename1.ui.RunnableWrapper.run(RunnableWrapper.java:120)
	at com.codename1.impl.CodenameOneThread.run(CodenameOneThread.java:176)`

It occurs when it invoked connect method of websocket.
(I'm using Eclipse).

**Comment by shannah** [comment]
Try doing a clean build.

**Comment by JrmyDev** [comment]
Already done!

**Comment by shannah** [comment]
The error indicates that it isn't finding the javase implementation - or they're not on the classpath.  Is this an old project that you are just adding the library to now?  If so the build script may not be adding the javase native files to the runtime classpath.

Do you get this issue if you create a fresh project and add websockets?

**Comment by JrmyDev** [comment]
Yes it's an old project. I've tried both to add javase native files to build path and with a fresh project ...
